import type { Metadata } from "next";

export const metadata: Metadata = { title: "Love Pattern Lab — Relationship self-reflection", description: "Relationship and personality self-reflection quizzes with free basic results and optional US$2.99 full reports." };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return <html lang="en"><body>{children}<style>{`
:root{--ink:#182725;--paper:#f4f0e8;--cream:#fffaf1;--coral:#ef745f;--line:rgba(24,39,37,.18)}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Segoe UI,Arial,sans-serif}a{color:inherit;text-decoration:none}.wrap{width:min(1100px,calc(100% - 40px));margin:auto}.nav{height:82px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}.brand{font-weight:800;letter-spacing:.13em}.hero{padding:90px 0 80px}.kicker{font-size:11px;font-weight:800;letter-spacing:.18em}.hero h1,.content h1{font-family:Georgia,serif;font-weight:500;font-size:clamp(50px,8vw,92px);line-height:.95;margin:24px 0}.hero h1 em{color:var(--coral);font-weight:500}.lead{max-width:650px;font-size:18px;line-height:1.7;color:#52615e}.badges{display:flex;gap:16px;flex-wrap:wrap;margin-top:30px}.badge{padding:12px 18px;border:1px solid var(--line);border-radius:999px;font-weight:700}.dark{background:var(--ink);color:var(--cream);padding:75px 0}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card{padding:28px;border:1px solid #ffffff33;min-height:280px;display:flex;flex-direction:column}.card h2{font-family:Georgia,serif;font-size:30px;font-weight:500}.card p{color:#aab3b0;line-height:1.6}.card a{margin-top:auto;color:#fff;font-weight:700}.footer{display:flex;justify-content:space-between;gap:20px;flex-wrap:wrap;border-top:1px solid #ffffff33;margin-top:42px;padding-top:26px;font-size:12px;color:#aab3b0}.footer nav{display:flex;gap:16px;flex-wrap:wrap}.content{max-width:780px;padding:70px 0 100px}.content h1{font-size:64px}.content h2{font-family:Georgia,serif;font-size:28px;margin-top:38px}.content p,.content li{font-size:16px;line-height:1.75;color:#596663}.content a{text-decoration:underline}.notice{padding:18px;background:#fffaf1;border:1px solid var(--line);margin:28px 0}@media(max-width:760px){.grid{grid-template-columns:1fr}.hero{padding:65px 0}.nav span{display:none}}
`}</style></body></html>;
}
